name: metroom
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  concentric_transition: ^1.0.3
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.7.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.1
  geocoder:
    git: https://github.com/aloisdeniel/flutter_geocoder.git
  geolocator: ^7.6.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  map_launcher: ^2.2.3
  provider: ^6.0.3
  razorpay_flutter: ^1.3.0
  salomon_bottom_bar: ^3.3.1
  scratcher: ^2.2.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  supabase: ^0.3.4+1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/logo/
    - assets/images/

# fonts:
#   - family: UniNeue
#     fonts:
#       - asset: assets/fonts/UniNeue-HeavyItalic.otf
#       - asset: assets/fonts/UniNeue-Light.otf
